name: CI-CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest kafka-python requests pyspark==3.5.0 pytest-cov

    - name: Run tests with coverage
      run: |
        PYTHONPATH=. pytest tests/ -v --cov=producer --cov=streaming_pipeline --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: tragiang/weather-pipeline:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  # deploy:
  #   needs: build
  #   runs-on: self-hosted
  #   if: github.ref == 'refs/heads/main'  # Disabled tạm để tránh wait runner
  #   steps:
  #     - uses: actions/checkout@v4
  #       ... (giữ nguyên steps cũ)